### ISSUE TITLE
Not able to install requirements

### ISSUE THREAD

**Issue by nikhil-salodkar** [kolk/AnsweringNaturally#2]
Hi,

**Can you please comment which version of softwares did you use for building this code base?**
While trying to install using requirements.txt I am getting possibly pip installation error such as : 
``ERROR: Command errored out with exit status 1:
     command: /home/nikhil_salodkar/.conda/envs/english-gen/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fwod729_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fwod729_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cb_c1f_g
         cwd: /tmp/pip-req-build-fwod729_/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-fwod729_/setup.py", line 60
        print(f'removing \'{path}\'')
                                   ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.``
When I tried to install recent version using conda and recent versions of OpenNMT-py, **padding data files is successful but errors start coming while running preprocessing scripts. The error are like** : ``ImportError: No module named 'torch.nn._functions'``

I tried installation using Python 3.5 and 3.6 and using different pytorch version including 1.2,1.3,1.5,1.6. I am using Ubuntu 18.04 with K80 gpu.

**Please help in resolving these installation issues.**
Thanks

**Comment by kolk** [comment]
Pytorch 0.4.1, torchtext 1.3 should resolve the issues.

**Comment by nikhil-salodkar** [comment]
Do you mean Pytorch 1.3 and torchtext 0.4? torchtext most recent version I can see is 0.6.

**Comment by damith92** [comment]
Hi, I also faced with the same problem and when I checked the pytorch documentation I could not find a module 'torch.nn._functions'.

**Comment by kolk** [comment]
Can you please check with torchtext 0.3.0 and pytorch version 0.4.1? Meanwhile, I'll update the code to be compatible with the latest pytorch version.

**Comment by damith92** [comment]
When I try using pytorch version 0.4.1 and torchtext 0.3.0, when the training starts this error comes.

Traceback (most recent call last):
  File "train.py", line 120, in <module>
    main(opt)
  File "train.py", line 51, in main
    single_main(opt, 0)
  File "/home/cognius_ai_gmail_com/qs/onmt/train_single.py", line 151, in main
    trainer.train(train_iter, valid_iter, opt.train_steps, opt.valid_steps)
  File "/home/cognius_ai_gmail_com/qs/onmt/trainer.py", line 172, in train
    report_stats)
  File "/home/cognius_ai_gmail_com/qs/onmt/trainer.py", line 272, in _gradient_accumulation
    outputs, attns = self.model(src, ans, tgt, src_lengths, ans_lengths, bptt=bptt)
  File "/home/cognius_ai_gmail_com/anaconda3/envs/test2/lib/python3.6/site-packages/torch/nn/modules/module.py", li
ne 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cognius_ai_gmail_com/qs/onmt/models/model.py", line 48, in forward
    enc_state_ans, memory_bank_ans, ans_lengths = self.encoder(ans, ans_lengths, "ans")
  File "/home/cognius_ai_gmail_com/anaconda3/envs/test2/lib/python3.6/site-packages/torch/nn/modules/module.py", li
ne 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cognius_ai_gmail_com/qs/onmt/encoders/rnn_encoder.py", line 65, in forward
    packed_emb = pack_padded_sequence_ans(emb, lengths)
  File "/home/cognius_ai_gmail_com/qs/onmt/utils/misc.py", line 126, in pack_padded_sequence_ans
    indices = torch.argsort(lengths, descending=True)
AttributeError: module 'torch' has no attribute 'argsort'

It seems in pytorch 0.4.1 , torch.argsort function is not there.

**Comment by kolk** [comment]
I have updated the code to be compatible with torch 1.5.0 and torchtext 0.6.0. It should be working smoothly now

**Comment by nikhil-salodkar** [comment]
Thanks a lot for updating the code. I tried it again and it started training correctly without any syntax errors. But this time the code is not able to identify and use GPU for training and using only CPU even though I checked that pytorch independently is identifying the GPU. The code where it identifies devices may have to be changed I guess. I will try it out when I get a chance.

**Comment by kolk** [comment]
Did you use the argument ```--gpu_ranks 0``` for training?

**Comment by nikhil-salodkar** [comment]
It worked! Thanks a lot for your help.
