### ISSUE TITLE
What does "accuracy score" mean in the paper?

### ISSUE THREAD

**Issue by SoyMark** [kolk/AnsweringNaturally#5]
Hi there, I'm doing an experiment on your dataset, and I'm trying to compare my results with yours. I have read your paper carefully, but there is no explanation of "accuracy score" in table 6.

**Comment by kolk** [comment]
Hey SoyMark, accuracy reported in the paper is the average word/token level accuracy on the validation set. It is the default metric is used in Opennmt-Py for validation.

**Comment by SoyMark** [comment]
Got it, thanks!
